### PR TITLE
Limit backoff so that it stops upon reaching max duration

### PR DESCRIPTION
**Pull request by abadyan-vonage**
Currently the retries never stop in case the write failed (for instance when there is a collision of field types).

### CODE REVIEW

**Comment by jpillora** [comment]
`backoff.Backoff` has an `Attempts()` method for this, though maybe it should be configurable (`RetryAttempts`), but defaults to `0` (infinite) so behaviour remains the same – for cases where you don't care how long it takes, just want to get it done. Also, seems gofmt needs to be run.

**Comment by abadyan-vonage** [comment]
I don't see the `Attempts` method you are referring to, only `Attempt` which returns the current one.
Can you explain what you mean please?

**Comment by jpillora** [comment]
Sorry, Attempt*

You could use it to say: if b.Attempt() == 10 log.Fatal, that is, give up
after 10 retrys. Comparing durations achieves the same thing though not as
clear IMO.

Alternatively, you could add a write timeout, checked at each back off
iteration and fatal once the total duration exceeds the timeout.

**Comment by abadyan-vonage** [comment]
@jpillora I fixed the code according to your suggestions.

**Comment by jpillora** [comment]
awesome! thanks @abadyan-vonage

**Comment by jpillora** [comment]
released as 0.1.2 and updated README help preview

**Pull request merged**
